### ISSUE TITLE
Non-english keyboard layouts aren't supported

### ISSUE THREAD

**Issue by defvs** [androidports/core#1]
# How to reproduce
Use a non-english keyboard (with accents, I'm using french virtual keyboard or physical keyboard)

# What is happening
When using a virtual keyboard, accents and things outside the english keyboard aren't registered and AndroidPorts enters nothing
When using a physical keyboard (I am using a bluetooth Nexus 9 keyboard, french AZERTY), the layout is english tho it is set to french in Android. No accent, as pressing any accented key is the english one.

Thanks for checking this issue; also, your ports are awesome ! Thanks !

**Comment by cab13140** [comment]
Seems to be keyboard-dependent, or maybe fixed in latest release ?
I was using an old google keyboard version, this might be the issue.
Issue closed.

## How to fix
Update to the latest version of GBoard, choose your layout in the input settings, and update AndroidPorts to the latest version

**Comment by cab13140** [comment]
Looks like it still isn't fixed. On physical keyboard, the letters are good, but accents, numbers and everything else aren't working

**Comment by ksmigrod** [comment]
Similar reaction with Polish keyboard layout.
I use Asus ZenPad 3S (Z500M) with NiZ Plum EC84 Bluetooth keyboard and External Keyboard Helper. Right Alt does not work as ISO Level 3 modificator.
In rare circumstances (happend to me twice inside an hour) modifiers lock, once "Ctrl" locked and the other time "Alt" locked, both times LO acted like both of keys were pressed.
Of the good news: LanguageTool extension works.
I was not able to lunch Idea, so I cannot confirm whether this problem is specific to LO or is it AndroPort wide.

**Comment by androidports** [comment]
AndroPorts supports inputing accented characters from version 1.2.0.
